services:
  - type: web
    name: flowermoon-transport
    runtime: docker
    plan: free
    region: frankfurt
    branch: hosting/render
    dockerfilePath: ./deploy/render/Dockerfile
    dockerContext: .
    healthCheckPath: /api/status
    autoDeployTrigger: off
    envVars:
      - key: PORT
        value: '8000'
